services:
  app:                    # The name of the service, can be anything
    image: todo-backend
    build: .              # Declares where to build the image from, in this case the current directory
    ports:                # Declares the ports to publish
      - 3123:3000